title: @5atoshiNakamoto's blog
description: A blog
theme: just-the-docs

url: https://5atoshiNakamoto.github.io/blog

aux_links:
  Template Repository: https://github.com/5atoshiNakamoto/blog

plugins:
  - jekyll-seo-tag
